# Generated by Django 4.1.3 on 2023-05-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_id", models.TextField(db_column="medicine_ID")),
                ("name", models.TextField()),
                ("cost", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "Medicine",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "Patient",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialist_id", models.TextField(db_column="specialist_ID")),
                ("first_name", models.TextField()),
                ("second_name", models.TextField()),
                ("patronymic", models.TextField(blank=True, null=True)),
                ("speciality", models.TextField()),
                ("home_address", models.TextField(blank=True, null=True)),
                ("phone_number", models.TextField()),
            ],
            options={
                "db_table": "Specialist",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.TextField(db_column="patient_ID")),
                ("specialist_id", models.TextField(db_column="specialist_ID")),
                ("is_first", models.BooleanField()),
                ("visit_id", models.TextField(db_column="visit_ID")),
                ("date", models.DateField()),
                ("anamnesis", models.TextField(blank=True, null=True)),
                ("diagnosis", models.TextField()),
                ("treatment", models.TextField(blank=True, null=True)),
                ("drugs_cost", models.FloatField(blank=True, null=True)),
                ("services_cost", models.FloatField()),
            ],
            options={
                "db_table": "Visit",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VisitMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_id", models.TextField(db_column="visit_ID")),
                ("medicine_id", models.TextField(db_column="medicine_ID")),
            ],
            options={
                "db_table": "Visit_Medicine",
                "managed": False,
            },
        ),
    ]
