# Generated by Django 4.1.3 on 2023-06-01 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
